mailcatcher:
  image: odaniait/mailcatcher-docker:latest
  ports:
    - "2525:2525"
    - "1080:1080"
mongodb:
  image: mongo:latest
  ports:
    - "127.0.0.1:27017:27017"
    - "127.0.0.1:27018:27018"
rockmongo:
  image: odaniait/rockmongo-docker:latest
  ports:
    - "8088:80"
  links:
    - mongodb
